{
  "language": "php",
  "php": 7.0,
  "before_script": [
    "cp .env.travis .env",
    "mysql -e 'create database testing;'",
    "composer self-update",
    "composer install --no-interaction",
    "composer update",
    "php artisan key:generate",
    "php artisan migrate",
    "php artisan db:seed",
    "npm install -g grunt-cli",
    "npm install -g bower",
    "npm install -g gulp ",
    "bower install",
    "npm install",
    "npm install node-sass",
    "gulp"
  ],
  "script": [
    "vendor/bin/phpunit"
  ],
  "group": "stable",
  "dist": "trusty",
  "os": "linux"
}

